import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import type { ChangeEvent, FormEvent } from "react";
import { getSession, getValidSession, rest, signOut, signedUrl, upload } from "@/lib/supabase";
import { ImagePlus, LogOut, Trash2, Video } from "lucide-react";
export const Route=createFileRoute("/perfil")({component:MyProfile});
type Profile={id:string;display_name:string;bio:string;city:string;state:string;interests:string[];avatar_path:string|null};
type Media={id:string;object_path:string;media_type:"photo"|"video";created_at:string};
function MyProfile(){
 const [profile,setProfile]=useState<Profile|null>(null),[media,setMedia]=useState<Media[]>([]),[urls,setUrls]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const session=getSession(),nav=useNavigate(),userId=session?.user.id;
 const load=useCallback(async()=>{if(!userId)return;try{const [p,m]=await Promise.all([rest<Profile[]>("profiles",`id=eq.${userId}&select=id,display_name,bio,city,state,interests,avatar_path`),rest<Media[]>("profile_media",`user_id=eq.${userId}&select=id,object_path,media_type,created_at&order=created_at.desc`)]);const current=p?.[0];setProfile(current??null);setMedia(m??[]);const signed=await Promise.all((m??[]).map(async item=>[item.id,await signedUrl(item.object_path)] as const));setUrls(Object.fromEntries(signed));}catch(e){setMessage(e instanceof Error?e.message:"Falha ao carregar perfil.");}},[userId]);
 useEffect(()=>{if(!userId){nav({to:"/entrar"});return;}void load();},[userId,nav,load]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!session||!profile)return;setBusy(true);setMessage("");const f=new FormData(e.currentTarget);try{await rest("profiles",`id=eq.${session.user.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({display_name:String(f.get("display_name")),bio:String(f.get("bio")),city:String(f.get("city")),state:String(f.get("state")),interests:String(f.get("interests")).split(",").map(s=>s.trim()).filter(Boolean)})});setMessage("Perfil salvo.");}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível salvar.");}finally{setBusy(false);}}
 async function add(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file||!session)return;setMessage("");const type=file.type.startsWith("image/")?"photo":file.type.startsWith("video/")?"video":null;if(!type){setMessage("Envie uma foto ou vídeo compatível.");return;}if(type==="photo"&&!["image/jpeg","image/png","image/webp"].includes(file.type)){setMessage("Fotos aceitas: JPG, PNG ou WEBP.");return;}if(type==="video"&&!["video/mp4","video/webm"].includes(file.type)){setMessage("Vídeos aceitos: MP4 ou WEBM.");return;}if(file.size>(type==="photo"?15:100)*1024*1024){setMessage("Arquivo excede o tamanho máximo permitido.");return;}setBusy(true);try{const path=`${session.user.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;await upload(path,file);await rest("rpc/register_profile_media","",{method:"POST",body:JSON.stringify({p_object_path:path,p_media_type:type,p_mime_type:file.type,p_size_bytes:file.size})});if(type==="photo"&&!profile?.avatar_path)await rest("profiles",`id=eq.${session.user.id}`,{method:"PATCH",body:JSON.stringify({avatar_path:path})});setMessage("Mídia enviada.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Falha no upload.");}finally{setBusy(false);}}
 async function remove(item:Media){if(!session||!confirm("Excluir esta mídia do seu perfil?"))return;try{const tokenSession=await getValidSession();if(!tokenSession)throw new Error("Sua sessão expirou. Entre novamente.");const response=await fetch(`${import.meta.env.VITE_SUPABASE_URL??"https://jquujdxypjylvghyuqco.supabase.co"}/storage/v1/object/profile-media/${item.object_path}`,{method:"DELETE",headers:{apikey:import.meta.env.VITE_SUPABASE_ANON_KEY??"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxdXVqZHh5cGp5bHZnaHl1cWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA4NjQ2NzcsImV4cCI6MjEwNjQ0MDY3N30.sxe7seiHqaI36zqb90yhA_43Gk3i9A8rG6UgvdnBbOc",Authorization:`Bearer ${tokenSession.access_token}`}});if(!response.ok)throw new Error("Não foi possível excluir o arquivo armazenado.");await rest("profile_media",`id=eq.${item.id}`,{method:"DELETE"});await load();}catch(e){setMessage(e instanceof Error?e.message:"Falha ao excluir mídia.");}}
 if(!session)return <main className="auth-page"><p>Carregando…</p></main>;
 return <main className="member-page"><header className="member-header"><a href="/"><img src="/sintoniamora-wordmark.webp" alt="Sintoniamora"/></a><button className="button button-outline" onClick={()=>{signOut();nav({to:"/"});}}><LogOut size={16}/> Sair</button></header><div className="member-content"><section className="member-heading"><span className="auth-kicker">MEU ESPAÇO</span><div className="member-avatar">{profile?.avatar_path&&media.find(x=>x.object_path===profile.avatar_path)?<img src={urls[media.find(x=>x.object_path===profile.avatar_path)!.id]} alt="Sua foto de perfil"/>:<span>{profile?.display_name?.slice(0,1)||"S"}</span>}</div><h1>Seu perfil</h1><p>Complete suas informações e compartilhe somente o que desejar.</p></section>{message&&<div className="form-message" role="status">{message}</div>}{profile&&<form className="profile-form" onSubmit={save}><label>Nome de exibição<input name="display_name" defaultValue={profile.display_name} required maxLength={40}/></label><label>Bio<textarea name="bio" defaultValue={profile.bio} maxLength={500} rows={4}/></label><div className="profile-fields"><label>Cidade<input name="city" defaultValue={profile.city}/></label><label>Estado<input name="state" defaultValue={profile.state} maxLength={2}/></label></div><label>Interesses, separados por vírgula<input name="interests" defaultValue={(profile.interests??[]).join(", ")}/></label><button className="button button-primary" disabled={busy}>{busy?"Salvando…":"Salvar perfil"}</button></form>}<section className="media-manager"><div><h2>Sua galeria</h2><p>Free: até 5 fotos e 2 vídeos. O servidor controla os limites.</p></div><div className="media-count"><span><ImagePlus size={16}/> {media.filter(x=>x.media_type==="photo").length}/5 fotos</span><span><Video size={16}/> {media.filter(x=>x.media_type==="video").length}/2 vídeos</span></div><label className="button button-primary upload-button">{busy?"Enviando…":"Adicionar foto ou vídeo"}<input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" disabled={busy} onChange={add} hidden/></label><div className="media-grid">{media.map(item=><article key={item.id} className="media-tile">{item.media_type==="photo"?<img src={urls[item.id]} alt="Mídia do perfil"/>:<video src={urls[item.id]} controls playsInline preload="none"/>}<div className="media-actions">{item.media_type==="photo"&&<button aria-label="Definir foto de perfil" title="Definir como foto de perfil" onClick={async()=>{if(!session||!profile)return;try{await rest("profiles",`id=eq.${session.user.id}`,{method:"PATCH",body:JSON.stringify({avatar_path:item.object_path})});setProfile({...profile,avatar_path:item.object_path});setMessage("Foto principal atualizada.");}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível atualizar a foto principal.");}}}>Perfil</button>}<button aria-label="Excluir mídia" onClick={()=>remove(item)}><Trash2 size={16}/></button></div></article>)}</div></section></div></main>;
}