import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import type { ChangeEvent, FormEvent } from "react";
import { getSession, rest, signOut, signedUrl, upload } from "@/lib/supabase";
import { ImagePlus, LogOut, Trash2, Video } from "lucide-react";
export const Route=createFileRoute("/perfil")({component:MyProfile});
type Profile={id:string;display_name:string;bio:string;city:string;state:string;interests:string[]};
type Media={id:string;object_path:string;media_type:"photo"|"video";created_at:string};
function MyProfile(){
 const [profile,setProfile]=useState<Profile|null>(null),[media,setMedia]=useState<Media[]>([]),[urls,setUrls]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const session=getSession(),nav=useNavigate();
 useEffect(()=>{if(!session){nav({to:"/entrar"});return;} void load();},[]);
 async function load(){if(!session)return;try{const [p,m]=await Promise.all([rest<Profile[]>("profiles",`id=eq.${session.user.id}&select=id,display_name,bio,city,state,interests`),rest<Media[]>("profile_media",`user_id=eq.${session.user.id}&select=id,object_path,media_type,created_at&order=created_at.desc`)]);const current=p?.[0];setProfile(current??null);setMedia(m??[]);const signed=await Promise.all((m??[]).map(async item=>[item.id,await signedUrl(item.object_path)] as const));setUrls(Object.fromEntries(signed));}catch(e){setMessage(e instanceof Error?e.message:"Falha ao carregar perfil.");}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!session||!profile)return;setBusy(true);setMessage("");const f=new FormData(e.currentTarget);try{await rest("profiles",`id=eq.${session.user.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({display_name:String(f.get("display_name")),bio:String(f.get("bio")),city:String(f.get("city")),state:String(f.get("state")),interests:String(f.get("interests")).split(",").map(s=>s.trim()).filter(Boolean)})});setMessage("Perfil salvo.");}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível salvar.");}finally{setBusy(false);}}
 async function add(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file||!session)return;setMessage("");const type=file.type.startsWith("image/")?"photo":file.type.startsWith("video/")?"video":null;if(!type){setMessage("Envie uma foto ou vídeo compatível.");return;}if(type==="photo"&&!["image/jpeg","image/png","image/webp"].includes(file.type)){setMessage("Fotos aceitas: JPG, PNG ou WEBP.");return;}if(type==="video"&&!["video/mp4","video/webm"].includes(file.type)){setMessage("Vídeos aceitos: MP4 ou WEBM.");return;}if(file.size>(type==="photo"?15:100)*1024*1024){setMessage("Arquivo excede o tamanho máximo permitido.");return;}setBusy(true);try{const path=`${session.user.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;await upload(path,file);await rest("rpc/register_profile_media","",{method:"POST",body:JSON.stringify({p_object_path:path,p_media_type:type,p_mime_type:file.type,p_size_bytes:file.size})});setMessage("Mídia enviada.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Falha no upload.");}finally{setBusy(false);}}
 async function remove(item:Media){if(!session||!confirm("Excluir esta mídia do seu perfil?"))return;try{await rest("profile_media",`id=eq.${item.id}`,{method:"DELETE"});await fetch(`${import.meta.env.VITE_SUPABASE_URL}/storage/v1/object/profile-media/${item.object_path}`,{method:"DELETE",headers:{apikey:import.meta.env.VITE_SUPABASE_ANON_KEY,Authorization:`Bearer ${session.access_token}`}});await load();}catch(e){setMessage(e instanceof Error?e.message:"Falha ao excluir mídia.");}}
 if(!session)return <main className="auth-page"><p>Carregando…</p></main>;
 return <main className="member-page"><header className="member-header"><a href="/"><img src="/sintoniamora-wordmark.webp" alt="Sintoniamora"/></a><button className="button button-outline" onClick={()=>{signOut();nav({to:"/"});}}><LogOut size={16}/> Sair</button></header><div className="member-content"><section className="member-heading"><span className="auth-kicker">MEU ESPAÇO</span><h1>Seu perfil</h1><p>Complete suas informações e compartilhe somente o que desejar.</p></section>{message&&<div className="form-message" role="status">{message}</div>}{profile&&<form className="profile-form" onSubmit={save}><label>Nome de exibição<input name="display_name" defaultValue={profile.display_name} required maxLength={40}/></label><label>Bio<textarea name="bio" defaultValue={profile.bio} maxLength={500} rows={4}/></label><div className="profile-fields"><label>Cidade<input name="city" defaultValue={profile.city}/></label><label>Estado<input name="state" defaultValue={profile.state} maxLength={2}/></label></div><label>Interesses, separados por vírgula<input name="interests" defaultValue={(profile.interests??[]).join(", ")}/></label><button className="button button-primary" disabled={busy}>{busy?"Salvando…":"Salvar perfil"}</button></form>}<section className="media-manager"><div><h2>Sua galeria</h2><p>Free: até 5 fotos e 2 vídeos. O servidor controla os limites.</p></div><div className="media-count"><span><ImagePlus size={16}/> {media.filter(x=>x.media_type==="photo").length}/5 fotos</span><span><Video size={16}/> {media.filter(x=>x.media_type==="video").length}/2 vídeos</span></div><label className="button button-primary upload-button">{busy?"Enviando…":"Adicionar foto ou vídeo"}<input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" disabled={busy} onChange={add} hidden/></label><div className="media-grid">{media.map(item=><article key={item.id} className="media-tile">{item.media_type==="photo"?<img src={urls[item.id]} alt="Mídia do perfil"/>:<video src={urls[item.id]} controls playsInline preload="none"/>}<button aria-label="Excluir mídia" onClick={()=>remove(item)}><Trash2 size={16}/></button></article>)}</div></section></div></main>;
}