/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// It may be regenerated when the route files change.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerfilFemininoRouteImport } from './routes/perfil-feminino'
import { Route as PerfilMasculinoRouteImport } from './routes/perfil-masculino'
import { Route as LiveRouteImport } from './routes/live'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const PerfilFemininoRoute = PerfilFemininoRouteImport.update({ id: '/perfil-feminino', path: '/perfil-feminino', getParentRoute: () => rootRouteImport } as any)
const PerfilMasculinoRoute = PerfilMasculinoRouteImport.update({ id: '/perfil-masculino', path: '/perfil-masculino', getParentRoute: () => rootRouteImport } as any)
const LiveRoute = LiveRouteImport.update({ id: '/live', path: '/live', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/perfil-feminino': typeof PerfilFemininoRoute
  '/perfil-masculino': typeof PerfilMasculinoRoute
  '/live': typeof LiveRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/perfil-feminino': typeof PerfilFemininoRoute
  '/perfil-masculino': typeof PerfilMasculinoRoute
  '/live': typeof LiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/perfil-feminino' | '/perfil-masculino' | '/live'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/perfil-feminino' | '/perfil-masculino' | '/live'
  id: '__root__' | '/' | '/perfil-feminino' | '/perfil-masculino' | '/live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PerfilFemininoRoute: typeof PerfilFemininoRoute
  PerfilMasculinoRoute: typeof PerfilMasculinoRoute
  LiveRoute: typeof LiveRoute
}
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/perfil-feminino': { id: '/perfil-feminino'; path: '/perfil-feminino'; fullPath: '/perfil-feminino'; preLoaderRoute: typeof PerfilFemininoRouteImport; parentRoute: typeof rootRouteImport }
    '/perfil-masculino': { id: '/perfil-masculino'; path: '/perfil-masculino'; fullPath: '/perfil-masculino'; preLoaderRoute: typeof PerfilMasculinoRouteImport; parentRoute: typeof rootRouteImport }
    '/live': { id: '/live'; path: '/live'; fullPath: '/live'; preLoaderRoute: typeof LiveRouteImport; parentRoute: typeof rootRouteImport }
  }
}
const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  PerfilFemininoRoute,
  PerfilMasculinoRoute,
  LiveRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
