/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ConfirmarEmailRouteImport } from './routes/confirmar-email'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PerfilFemininoRouteImport } from './routes/perfil-feminino'
import { Route as PerfilMasculinoRouteImport } from './routes/perfil-masculino'
import { Route as PerfilPublicoRouteImport } from './routes/perfil-publico'
import { Route as PlanosRouteImport } from './routes/planos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarEmailRoute = ConfirmarEmailRouteImport.update({
  id: '/confirmar-email',
  path: '/confirmar-email',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilFemininoRoute = PerfilFemininoRouteImport.update({
  id: '/perfil-feminino',
  path: '/perfil-feminino',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilMasculinoRoute = PerfilMasculinoRouteImport.update({
  id: '/perfil-masculino',
  path: '/perfil-masculino',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilPublicoRoute = PerfilPublicoRouteImport.update({
  id: '/perfil-publico',
  path: '/perfil-publico',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/dashboard': typeof DashboardRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/feed': typeof FeedRoute
  '/live': typeof LiveRoute
  '/mensagens': typeof MensagensRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/perfil-feminino': typeof PerfilFemininoRoute
  '/perfil-masculino': typeof PerfilMasculinoRoute
  '/perfil-publico': typeof PerfilPublicoRoute
  '/planos': typeof PlanosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/dashboard': typeof DashboardRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/feed': typeof FeedRoute
  '/live': typeof LiveRoute
  '/mensagens': typeof MensagensRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/perfil-feminino': typeof PerfilFemininoRoute
  '/perfil-masculino': typeof PerfilMasculinoRoute
  '/perfil-publico': typeof PerfilPublicoRoute
  '/planos': typeof PlanosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/dashboard': typeof DashboardRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/feed': typeof FeedRoute
  '/live': typeof LiveRoute
  '/mensagens': typeof MensagensRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/perfil-feminino': typeof PerfilFemininoRoute
  '/perfil-masculino': typeof PerfilMasculinoRoute
  '/perfil-publico': typeof PerfilPublicoRoute
  '/planos': typeof PlanosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajuda'
    | '/cadastro'
    | '/confirmar-email'
    | '/dashboard'
    | '/entrar'
    | '/explorar'
    | '/feed'
    | '/live'
    | '/mensagens'
    | '/notificacoes'
    | '/perfil'
    | '/perfil-feminino'
    | '/perfil-masculino'
    | '/perfil-publico'
    | '/planos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ajuda'
    | '/cadastro'
    | '/confirmar-email'
    | '/dashboard'
    | '/entrar'
    | '/explorar'
    | '/feed'
    | '/live'
    | '/mensagens'
    | '/notificacoes'
    | '/perfil'
    | '/perfil-feminino'
    | '/perfil-masculino'
    | '/perfil-publico'
    | '/planos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajuda'
    | '/cadastro'
    | '/confirmar-email'
    | '/dashboard'
    | '/entrar'
    | '/explorar'
    | '/feed'
    | '/live'
    | '/mensagens'
    | '/notificacoes'
    | '/perfil'
    | '/perfil-feminino'
    | '/perfil-masculino'
    | '/perfil-publico'
    | '/planos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AjudaRoute: typeof AjudaRoute
  CadastroRoute: typeof CadastroRoute
  ConfirmarEmailRoute: typeof ConfirmarEmailRoute
  DashboardRoute: typeof DashboardRoute
  EntrarRoute: typeof EntrarRoute
  ExplorarRoute: typeof ExplorarRoute
  FeedRoute: typeof FeedRoute
  LiveRoute: typeof LiveRoute
  MensagensRoute: typeof MensagensRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PerfilRoute: typeof PerfilRoute
  PerfilFemininoRoute: typeof PerfilFemininoRoute
  PerfilMasculinoRoute: typeof PerfilMasculinoRoute
  PerfilPublicoRoute: typeof PerfilPublicoRoute
  PlanosRoute: typeof PlanosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar-email': {
      id: '/confirmar-email'
      path: '/confirmar-email'
      fullPath: '/confirmar-email'
      preLoaderRoute: typeof ConfirmarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-feminino': {
      id: '/perfil-feminino'
      path: '/perfil-feminino'
      fullPath: '/perfil-feminino'
      preLoaderRoute: typeof PerfilFemininoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-masculino': {
      id: '/perfil-masculino'
      path: '/perfil-masculino'
      fullPath: '/perfil-masculino'
      preLoaderRoute: typeof PerfilMasculinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-publico': {
      id: '/perfil-publico'
      path: '/perfil-publico'
      fullPath: '/perfil-publico'
      preLoaderRoute: typeof PerfilPublicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AjudaRoute: AjudaRoute,
  CadastroRoute: CadastroRoute,
  ConfirmarEmailRoute: ConfirmarEmailRoute,
  DashboardRoute: DashboardRoute,
  EntrarRoute: EntrarRoute,
  ExplorarRoute: ExplorarRoute,
  FeedRoute: FeedRoute,
  LiveRoute: LiveRoute,
  MensagensRoute: MensagensRoute,
  NotificacoesRoute: NotificacoesRoute,
  PerfilRoute: PerfilRoute,
  PerfilFemininoRoute: PerfilFemininoRoute,
  PerfilMasculinoRoute: PerfilMasculinoRoute,
  PerfilPublicoRoute: PerfilPublicoRoute,
  PlanosRoute: PlanosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
